name: mcbayes tests

on:
  push:
    branches:
      - 'main'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.8'
      - name: Run tests
        run: julia -e 'using Pkg; Pkg.activate("."); Pkg.test();'
