name: mcbayes tests

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out github
        uses: actions/checkout@v3

      - name: Check out BridgeStan
        uses: actions/checkout@v3
        with:
          repository: roualdes/bridgestan
          submodules: recursive
          ref: "v1.0.0"
          path: bridgestan

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.8'

      - name: Stan build caching
        uses: actions/cache@v3
        id: stan-cache
        with:
          path: ./bridgestan/stan/
          key: stan-${{ runner.os }}-${{ hashFiles('bridgestan/stan/src/stan/version.hpp') }}

      - name: Cache julia artifacts (test_models)
        uses: actions/cache@v3
        id: julia-artifacts-cache
        with:
          path: ~/.julia/artifacts
          key: julia-artifacts-${{ runner.os }}-${{ hashFiles('**/Project.toml', '**/Artifacts.toml') }}

      - name: Install BridgeStan
        run: julia --project=./test -e 'using Pkg; Pkg.develop(PackageSpec(path="bridgestan", subdir="julia")); Pkg.instantiate();'

      - name: Run tests
        run: julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.test()'
