name: mcbayes tests

on:
  push:
    branches:
      - 'main'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.8'
      - name: Install dependencies
        run: julia --project=test/ -e 'using Pkg; Pkg.develop(PackageSpec(url="https://github.com/roualdes/bridgestan", subdir="julia")); Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Run tests
        run: julia -e 'using Pkg; Pkg.activate("."); Pkg.test();'
